## Decision Tree

In [1]:
# import modules
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
import os
import matplotlib.pyplot as plt
from sklearn import tree, metrics

import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler 
from sklearn.metrics import confusion_matrix, classification_report 
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import NearMiss 

# Cross Validation packages
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score


# for plotting
import matplotlib.pyplot as plt
from sklearn.svm import SVC

# import module for gridsearch (to find optimal hyper-parameters)
from sklearn.model_selection import GridSearchCV

# import module (to test execution time of a codeblock to run)
import time

import warnings

from sklearn.model_selection import StratifiedKFold
from sklearn.svm import SVC

/opt/tljh/user/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/opt/tljh/user/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.ensemble.bagging module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
  warnings.warn(message, FutureWarning)
/opt/tljh/user/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.ensemble.base module is  deprecated in version 0.22 and will be removed in

In [2]:
# packages for Receiver Operating Characteristic (ROC) with cross validation
# source: https://scikit-learn.org/0.18/auto_examples/model_selection/plot_roc_crossval.html
print(__doc__)

import numpy as np
from scipy import interp
import matplotlib.pyplot as plt
from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import plot_roc_curve

Automatically created module for IPython interactive environment


# Data before Normalization

In [3]:
df = pd.read_csv("census_covid_cat_final.csv")

In [4]:
df.head()

Full Name    Country Name    State State Abbr  \
0  Autauga County, Alabama  Autauga County  Alabama         AL   
1  Baldwin County, Alabama  Baldwin County  Alabama         AL   
2  Barbour County, Alabama  Barbour County  Alabama         AL   
3     Bibb County, Alabama     Bibb County  Alabama         AL   
4   Blount County, Alabama   Blount County  Alabama         AL   

    Total Population    Households SNAP    Estimated Individuals SNAP   \
0               54571               2802                          7509   
1              182265               6644                         16344   
2               27457               2468                          6096   
3               22915                933                          2426   
4               57322               2244                          5902   

    Total Citizen Educated in US    Citizen Less than High School  Education   \
0                           36757                                        4521   
1                          143022                                       13997   
2                           18434                                        4960   
3                           15859                                        2833   
4                           39475                                        7980   

    Citizen High School  Graduate   ...  Female Median Age  \
0                            12363  ...               37.9   
1                            39771  ...               42.2   
2                             6549  ...               41.6   
3                             6958  ...               39.5   
4                            12740  ...               40.0   

    Total Households    Average Household Size    Total Families   \
0               20221                         3             14613   
1               73180                         2             41898   
2                9820                         2              6015   
3                7953                         3              5201   
4               21578                         3             14106   

   Total Confirmed Cases  Total Deaths  Case Rate per 1000  Death Rate 1000  \
0                      0             0               7.330            0.147   
1                    400             8               2.200            0.049   
2                    401             9               9.579            0.036   
3                    263             1               5.280            0.044   
4                    121             1               2.268            0.017   

   Case Rate Categories   Death Rate Categories  
0                      2                      2  
1                      2                      1  
2                      3                      1  
3                      2                      1  
4                      2                      1  

[5 rows x 43 columns]

In [5]:
df.dtypes

Full Name                                      object
Country Name                                   object
State                                          object
State Abbr                                     object
 Total Population                               int64
 Households SNAP                                int64
 Estimated Individuals SNAP                     int64
 Total Citizen Educated in US                   int64
 Citizen Less than High School  Education       int64
 Citizen High School  Graduate                  int64
 Citizen Some College  Education                int64
 Citizen College Degree                         int64
 Citizen Graduate or Professional Degree        int64
 Total Citizen Income                           int64
 Citizen No Income                              int64
Citizen Income 1-9999                           int64
Citizen Income 10000-14999                      int64
Citizen Income 15000-24999                      int64
Citizen Income 25000-34999  

In [6]:
# trim the spaces of the cells from the csv file
df.columns = df.columns.to_series().apply(lambda x: x.strip())

In [7]:
# need to change int64 to cat type for target vars
df['Case Rate Categories'] = df['Case Rate Categories'].astype('category')
df['Death Rate Categories'] = df['Death Rate Categories'].astype('category')

In [8]:
#df.dtypes
#check to see if types changed to cat -- YES

<a id = ""> <h2> 1.0 Basic Model Decision Tree Classifier </h2> </a>

__Build the Model__

# Target Variable is 'Death Rate Categories'

In [9]:
# change these features to normalized ones 
features = ['Total Population','Households SNAP','Estimated Individuals SNAP','Total Citizen Educated in US',
                       'Citizen Less than High School  Education','Citizen High School  Graduate',
                       'Citizen Some College  Education','Citizen College Degree','Citizen Graduate or Professional Degree',
                       'Total Citizen Income','Citizen No Income','Citizen Income 1-9999','Citizen Income 10000-14999',
                       'Citizen Income 15000-24999','Citizen Income 25000-34999','Citizen Income 35000-49999',
                       'Citizen Income 50000-64999','Citizen Income 65000-74999','Citizen Income over 75000',
                       'One Race Population','White Race','Black Race','Native American Race','Asian Race',
                       'Pacific Islander Race','Other Race Alone','Hispanic or Latino','Median Age', 
                        'Male Median Age','Female Median Age','Total Households',
                       'Average Household Size','Total Families']

X = df[features] # from list above
Y = df.iloc[:, -1] # Target is the last column in the dataframe: ''

In [10]:
# Split dataset into training set and test set 
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=2019)

In [11]:
df1 = df.drop(['Case Rate Categories'], axis=1)
#df1.head() check to see if the column was dropped 

In [12]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [13]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.43312101910828027


In [14]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.67      0.61      0.64       390
           1       0.36      0.42      0.39       203
           2       0.29      0.29      0.29       228
           3       0.18      0.19      0.19        89
           4       0.07      0.07      0.07        27
           5       0.00      0.00      0.00         5

    accuracy                           0.43       942
   macro avg       0.26      0.26      0.26       942
weighted avg       0.45      0.43      0.44       942



In [15]:
print(metrics.confusion_matrix(y_test, y_pred))

[[238  58  72  15   6   1]
 [ 40  85  53  22   2   1]
 [ 51  65  66  31  12   3]
 [ 20  23  22  17   7   0]
 [  7   5   8   5   2   0]
 [  0   0   3   2   0   0]]


# Creating Graph of Decision Tree

In [16]:
# source: https://www.datacamp.com/community/tutorials/decision-tree-classification-python
from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus
dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True, feature_names = features,class_names=['0','1'])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png('covid_census.png')
Image(graph.create_png())

/opt/tljh/user/lib/python3.6/site-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)


IndexError: list index out of range

<a id = "800110"> <h2> 1.1 Oversampling (SMOTE) </h2> </a>
We oversample the <b> training </b> dataset, because the classes within our target variable 'Revenue' are imbalanced:
* class 0: 84.53%
* class 1: 15.47%

Fore more information, click on detailed information from Prof. Jie Tao [link](https://github.com/DrJieTao/ba545-docs/blob/master/competition2/handling_imbalanced_data_part2.ipynb)

In [ ]:
# Split dataset into training set and test set 
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=2019) 

sm = SMOTE(random_state = 2019) 
X_train_res, y_train_res = sm.fit_sample(X_train, y_train) 

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape)) 
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape)) 
  
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0)))

The SMOTE Algorithm has oversampled the instances in the minority class and made it equal to majority class:
* Both classes (0 & 1) now have 7291 instances, the <b> training </b> dataset is balanced.
* Class 1 increased from 1340 instances to 7291 instances, an increase of 5951 instances of class 1.

In [ ]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train_res, y_train_res)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# print classification report 
print(classification_report(y_test, y_pred))

## Cross Validation Using KFold </b>
For more information on the topic, please click the following [link](https://stackabuse.com/cross-validation-and-grid-search-for-model-selection-in-python/).
<br> The details of the package are noted [here](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html).

<a id = "800130"> <h2> 1.3 Cross Validation (Oversampling)  </h2> </a>

In [ ]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
#result = cross_val_score(gnb, X, Y, cv=kfold, scoring='accuracy')
result = cross_val_score(clf, X_train_res, y_train_res, cv=kfold, scoring='accuracy')

print('--------------------------------------------------------------------------')
print('All the accuracy results:')
print('--------------------------------------------------------------------------')
print(result, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the accuracy results:')
print('--------------------------------------------------------------------------')
print(round(result.mean(), 4), '\n')

print('--------------------------------------------------------------------------')
print('Conclusion: the average of the accuracy changed after applying Kfold:')
print('--------------------------------------------------------------------------')
print('from:')
print(round(metrics.accuracy_score(y_test, y_pred), 5))
print('to:')
print(round(result.mean(), 5))
print('This is because we only use: {0:0.2f}% of our dataset to train the model!'.format(((k_fold_split-1)/k_fold_split)*100))

In [ ]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
#result = cross_val_score(clf, X, Y, cv=kfold, scoring='accuracy')
# note: only a single metric is permitted for parameter 'scoring'
# for all parameters for scoring, see source:https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
result_f1_weighted = cross_val_score(clf, X_train_res, y_train_res, cv=kfold, scoring='f1_weighted')
print('--------------------------------------------------------------------------')
print('All the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(result_f1_weighted, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(round(result_f1_weighted.mean(), 4), '\n')

<a id = "800140"> <h2> 1.4 Cross Validation (Undersampling)  </h2> </a>

In [ ]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
#result = cross_val_score(clf, X, Y, cv=kfold, scoring='accuracy')
result = cross_val_score(clf2, X_train_miss, y_train_miss, cv=kfold, scoring='accuracy')

print('--------------------------------------------------------------------------')
print('All the accuracy results:')
print('--------------------------------------------------------------------------')
print(result, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the accuracy results:')
print('--------------------------------------------------------------------------')
print(round(result.mean(), 4), '\n')

print('--------------------------------------------------------------------------')
print('Conclusion: the average of the accuracy changed after applying Kfold:')
print('--------------------------------------------------------------------------')
print('from:')
print(round(metrics.accuracy_score(y_test, y_pred), 5))
print('to:')
print(round(result.mean(), 5))
print('This is because we only use: {0:0.2f}% of our dataset to train the model!'.format(((k_fold_split-1)/k_fold_split)*100))

In [ ]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
#result = cross_val_score(clf, X, Y, cv=kfold, scoring='accuracy')
# note: only a single metric is permitted for parameter 'scoring'
# for all parameters for scoring, see source:https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
result_f1_weighted = cross_val_score(clf2, X_train_miss, y_train_miss, cv=kfold, scoring='f1_weighted')
print('--------------------------------------------------------------------------')
print('All the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(result_f1_weighted, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(round(result_f1_weighted.mean(), 4), '\n')

<a id = "800150"> <h2> 1.5 Model Tuning (Hyperparameters) </h2> </a>
___


<b> Define Grid

In [ ]:
criterion= ['gini', 'entropy'] 
splitter= ['best', 'random'] 
max_depth= [3,5,10] 
param_grid = dict(criterion=criterion, splitter=splitter, max_depth=max_depth)

<b> Hyper-parameter tweaking on oversampled training set

In [ ]:
# set the start time
start = time.time()

# define the model
clf = DecisionTreeClassifier()

# Create a grid search object
grid = GridSearchCV(estimator=clf, param_grid=param_grid, cv = 3, n_jobs=-1)

# Fit the grid search (Fitting your model to the training data)
grid_result = grid.fit(X_train_res, y_train_res)

# define each optimal parameter as a new variable
optimal_criterion = grid.best_estimator_.get_params()['criterion']
optimal_splitter = grid.best_estimator_.get_params()['splitter']
optimal_max_depth = grid.best_estimator_.get_params()['max_depth']

# Summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

# get the time it takes for the gridsearch to run
# source: https://blog.softhints.com/python-test-performance-and-measure-time-elapsed-in-seconds/
# set the end time
end = time.time()

# get the elapsed execution time
execution_time = end - start
print("--- Execution time: ---")
print ('--- %0.3fms. --- ' % ( execution_time*1000.))
print("--- %s seconds ---" % (execution_time))
print("--- %s minutes ---" % (execution_time/60))

<b> Applying the optimal hyper-parameters on oversampled training set

In [ ]:
# apply the optimal hyper-parameters to the Logistic Regression Model
clf3 = DecisionTreeClassifier(criterion=optimal_criterion, splitter=optimal_splitter, max_depth=optimal_max_depth)

# fit/train the model with oversampled training set
clf3.fit(X_train_res, y_train_res)

# predict the testing set
y_pred=clf3.predict(X_test)

# print out the classification report
print(classification_report(y_test, y_pred))

# Target Variable is 'Case Rate Categories'

In [ ]:
#df = pd.read_csv("census_covid_cat_final.csv")

In [ ]:
#df.info()

In [ ]:
# drop Death Rate Categories -- need Case Rate Categories to be the target variable
df2 = df.iloc[:, :-1]

In [ ]:
X = df2.iloc[:, 4:-7] # Features is all columns in the dataframe except the last 6 columns
Y = df2.iloc[:, -1] # Target is the last column in the dataframe: 'Case Rate Categories'

In [ ]:
# Split dataset into training set and test set 
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=2019)

In [ ]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [ ]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

In [ ]:
print(metrics.classification_report(y_test, y_pred))

In [ ]:
print(metrics.confusion_matrix(y_test, y_pred))

<a id = "800110"> <h2> 1.1 Oversampling (SMOTE) </h2> </a>
We oversample the <b> training </b> dataset, because the classes within our target variable 'Revenue' are imbalanced:
* class 0: 84.53%
* class 1: 15.47%

Fore more information, click on detailed information from Prof. Jie Tao [link](https://github.com/DrJieTao/ba545-docs/blob/master/competition2/handling_imbalanced_data_part2.ipynb)

In [ ]:
# Split dataset into training set and test set 
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=2019) 

sm = SMOTE(random_state = 2019) 
X_train_res, y_train_res = sm.fit_sample(X_train, y_train) 

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape)) 
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape)) 
  
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0)))

The SMOTE Algorithm has oversampled the instances in the minority class and made it equal to majority class:
* Both classes (0 & 1) now have 7291 instances, the <b> training </b> dataset is balanced.
* Class 1 increased from 1340 instances to 7291 instances, an increase of 5951 instances of class 1.

In [ ]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train_res, y_train_res)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# print classification report 
print(classification_report(y_test, y_pred))

## Cross Validation Using KFold </b>
For more information on the topic, please click the following [link](https://stackabuse.com/cross-validation-and-grid-search-for-model-selection-in-python/).
<br> The details of the package are noted [here](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html).

<a id = "800130"> <h2> 1.3 Cross Validation (Oversampling)  </h2> </a>

In [ ]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
#result = cross_val_score(gnb, X, Y, cv=kfold, scoring='accuracy')
result = cross_val_score(clf, X_train_res, y_train_res, cv=kfold, scoring='accuracy')

print('--------------------------------------------------------------------------')
print('All the accuracy results:')
print('--------------------------------------------------------------------------')
print(result, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the accuracy results:')
print('--------------------------------------------------------------------------')
print(round(result.mean(), 4), '\n')

print('--------------------------------------------------------------------------')
print('Conclusion: the average of the accuracy changed after applying Kfold:')
print('--------------------------------------------------------------------------')
print('from:')
print(round(metrics.accuracy_score(y_test, y_pred), 5))
print('to:')
print(round(result.mean(), 5))
print('This is because we only use: {0:0.2f}% of our dataset to train the model!'.format(((k_fold_split-1)/k_fold_split)*100))

In [ ]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
#result = cross_val_score(clf, X, Y, cv=kfold, scoring='accuracy')
# note: only a single metric is permitted for parameter 'scoring'
# for all parameters for scoring, see source:https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
result_f1_weighted = cross_val_score(clf, X_train_res, y_train_res, cv=kfold, scoring='f1_weighted')
print('--------------------------------------------------------------------------')
print('All the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(result_f1_weighted, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(round(result_f1_weighted.mean(), 4), '\n')

<a id = "800140"> <h2> 1.4 Cross Validation (Undersampling)  </h2> </a>

In [ ]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
#result = cross_val_score(clf, X, Y, cv=kfold, scoring='accuracy')
result = cross_val_score(clf2, X_train_miss, y_train_miss, cv=kfold, scoring='accuracy')

print('--------------------------------------------------------------------------')
print('All the accuracy results:')
print('--------------------------------------------------------------------------')
print(result, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the accuracy results:')
print('--------------------------------------------------------------------------')
print(round(result.mean(), 4), '\n')

print('--------------------------------------------------------------------------')
print('Conclusion: the average of the accuracy changed after applying Kfold:')
print('--------------------------------------------------------------------------')
print('from:')
print(round(metrics.accuracy_score(y_test, y_pred), 5))
print('to:')
print(round(result.mean(), 5))
print('This is because we only use: {0:0.2f}% of our dataset to train the model!'.format(((k_fold_split-1)/k_fold_split)*100))

In [ ]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
#result = cross_val_score(clf, X, Y, cv=kfold, scoring='accuracy')
# note: only a single metric is permitted for parameter 'scoring'
# for all parameters for scoring, see source:https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
result_f1_weighted = cross_val_score(clf2, X_train_miss, y_train_miss, cv=kfold, scoring='f1_weighted')
print('--------------------------------------------------------------------------')
print('All the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(result_f1_weighted, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(round(result_f1_weighted.mean(), 4), '\n')

<a id = "800150"> <h2> 1.5 Model Tuning (Hyperparameters) </h2> </a>
___


<b> Define Grid

In [ ]:
criterion= ['gini', 'entropy'] 
splitter= ['best', 'random'] 
max_depth= [3,5,10] 
param_grid = dict(criterion=criterion, splitter=splitter, max_depth=max_depth)

<b> Hyper-parameter tweaking on oversampled training set

In [ ]:
# set the start time
start = time.time()

# define the model
clf = DecisionTreeClassifier()

# Create a grid search object
grid = GridSearchCV(estimator=clf, param_grid=param_grid, cv = 3, n_jobs=-1)

# Fit the grid search (Fitting your model to the training data)
grid_result = grid.fit(X_train_res, y_train_res)

# define each optimal parameter as a new variable
optimal_criterion = grid.best_estimator_.get_params()['criterion']
optimal_splitter = grid.best_estimator_.get_params()['splitter']
optimal_max_depth = grid.best_estimator_.get_params()['max_depth']

# Summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

# get the time it takes for the gridsearch to run
# source: https://blog.softhints.com/python-test-performance-and-measure-time-elapsed-in-seconds/
# set the end time
end = time.time()

# get the elapsed execution time
execution_time = end - start
print("--- Execution time: ---")
print ('--- %0.3fms. --- ' % ( execution_time*1000.))
print("--- %s seconds ---" % (execution_time))
print("--- %s minutes ---" % (execution_time/60))

<b> Applying the optimal hyper-parameters on oversampled training set

In [ ]:
# apply the optimal hyper-parameters to the Logistic Regression Model
clf3 = DecisionTreeClassifier(criterion=optimal_criterion, splitter=optimal_splitter, max_depth=optimal_max_depth)

# fit/train the model with oversampled training set
clf3.fit(X_train_res, y_train_res)

# predict the testing set
y_pred=clf3.predict(X_test)

# print out the classification report
print(classification_report(y_test, y_pred))