# Decision Tree #

<b> Table of Contents: </b>
<br> [Import and Load the Dataset](#10)
<br> [Data Exploration and Analysis](#20)
<br> [Decision Tree Model: Target Variable - COVID Confirmed Cases](#30)


<a id = "10"> <h2> Import and Load the Dataset </h2> </a>
___

_Import Modules_

In [36]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.preprocessing import Normalizer

_Loading the Dataset_

In [37]:
# load the dataset
df_tristate_cases = pd.read_csv("tristate_final_data.csv")

In [38]:
df_tristate_cases.head()

NAME  Covid Confirmed Cases  Covid Deaths   \
0       Albany County, New York                  87943           3989   
1     Allegany County, New York                   2601            126   
2        Bronx County, New York                2544478         234021   
3       Broome County, New York                  24218           1802   
4  Cattaraugus County, New York                   3875            128   

   Population  Covid Case Rate (per 1000)  Covid Death Rate (per 1000)  \
0      304204                  289.092188                    13.112911   
1       48946                   53.140195                     2.574266   
2     1385108                 1837.024983                   168.955056   
3      200600                  120.727817                     8.983051   
4       80317                   48.246324                     1.593685   

    Households SNAP    Estimated Individuals SNAP   \
0              15087                         34247   
1               2994                          7305   
2             184934                        512267   
3              13226                         30684   
4               5801                         13980   

    Total Citizen Educated in US    Citizen Less than High School  Education   \
0                          204833                                       15255   
1                           30331                                        3219   
2                          927374                                      264309   
3                          129802                                       12429   
4                           53201                                        6188   

   ...   Asian Race    Pacific Islander Race    Other Race Alone   \
0  ...            98                     4744                7647   
1  ...             9                      206                 557   
2  ...          1288                   351011               73243   
3  ...            82                     1912                5087   
4  ...            15                      305                1363   

    Hispanic or Latino   Median Age  Male Median Age  Female Median Age  \
0                289287        38.5             36.8               40.0   
1                 48276        37.8             36.2               39.2   
2                643695        32.8             30.6               34.9   
3                193822        40.2             38.1               42.2   
4                 78972        40.7             39.8               41.6   

    Total Households    Average Household Size    Total Families   
0              126251                         2             60631  
1               18208                         2             10576  
2              483449                         3            368196  
3               82167                         2             40559  
4               32263                         2             18801  

[5 rows x 39 columns]

<a id = "20"> <h2> Data Exploration and Analysis </h2> </a>
___

In [39]:
df_tristate_cases.describe()

Covid Confirmed Cases  Covid Deaths     Population  \
count           9.100000e+01      91.000000  9.100000e+01   
mean            3.456057e+05   24234.989011  3.488362e+05   
std             7.060102e+05   59348.612086  4.688670e+05   
min             3.040000e+02       0.000000  4.836000e+03   
25%             5.696000e+03     222.500000  6.495600e+04   
50%             3.653600e+04    1815.000000  1.492650e+05   
75%             2.973320e+05   19315.000000  4.678780e+05   
max             3.587059e+06  347696.000000  2.504700e+06   

       Covid Case Rate (per 1000)  Covid Death Rate (per 1000)  \
count                   91.000000                    91.000000   
mean                   494.782434                    30.009640   
std                    569.681260                    36.520683   
min                     16.823179                     0.000000   
25%                     88.358613                     3.932980   
50%                    230.123991                    13.455905   
75%                    698.363567                    48.039981   
max                   2523.785079                   168.955056   

        Households SNAP    Estimated Individuals SNAP   \
count          91.000000                     91.000000   
mean        18293.857143                  47275.835165   
std         35039.232590                  93199.614618   
min           112.000000                    235.000000   
25%          3339.000000                   8134.500000   
50%          6896.000000                  17693.000000   
75%         16277.000000                  41301.500000   
max        231794.000000                 623526.000000   

        Total Citizen Educated in US   \
count                    9.100000e+01   
mean                     2.451077e+05   
std                      3.390094e+05   
min                      3.604000e+03   
25%                      4.454750e+04   
50%                      9.567900e+04   
75%                      3.225095e+05   
max                      1.789355e+06   

        Citizen Less than High School  Education   \
count                                   91.000000   
mean                                 30821.109890   
std                                  58806.714504   
min                                    441.000000   
25%                                   4884.500000   
50%                                   9121.000000   
75%                                  29749.500000   
max                                 345445.000000   

        Citizen High School  Graduate   ...   Asian Race   \
count                        91.000000  ...     91.000000   
mean                      65796.329670  ...    145.461538   
std                       84838.264728  ...    264.790622   
min                        1155.000000  ...      2.000000   
25%                       15221.000000  ...     16.500000   
50%                       31537.000000  ...     37.000000   
75%                       85696.000000  ...    164.000000   
max                      461228.000000  ...   1530.000000   

        Pacific Islander Race    Other Race Alone    Hispanic or Latino   \
count                91.000000           91.000000          9.100000e+01   
mean              24173.087912        10097.010989          2.889334e+05   
std               57081.322656        17237.898715          3.622369e+05   
min                   4.000000           53.000000          4.785000e+03   
25%                 526.000000         1006.500000          6.262450e+04   
50%                2211.000000         3036.000000          1.266640e+05   
75%               18173.000000        11900.000000          3.770460e+05   
max              351011.000000       100913.000000          2.008415e+06   

       Median Age  Male Median Age  Female Median Age   Total Households   \
count   91.000000        91.000000          91.000000           91.000000   
mean    40.156044        38.840659          41.445055       130804.417582   
std      3.098071        

In [40]:
df_tristate_cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 39 columns):
NAME                                          91 non-null object
Covid Confirmed Cases                         91 non-null int64
Covid Deaths                                  91 non-null int64
Population                                    91 non-null int64
Covid Case Rate (per 1000)                    91 non-null float64
Covid Death Rate (per 1000)                   91 non-null float64
 Households SNAP                              91 non-null int64
 Estimated Individuals SNAP                   91 non-null int64
 Total Citizen Educated in US                 91 non-null int64
 Citizen Less than High School  Education     91 non-null int64
 Citizen High School  Graduate                91 non-null int64
 Citizen Some College  Education              91 non-null int64
 Citizen College Degree                       91 non-null int64
 Citizen Graduate or Professional Degree      91 non-null in

In [41]:
df_tristate_cases.columns.values

array(['NAME', 'Covid Confirmed Cases', 'Covid Deaths ', 'Population',
       'Covid Case Rate (per 1000)', 'Covid Death Rate (per 1000)',
       ' Households SNAP ', ' Estimated Individuals SNAP ',
       ' Total Citizen Educated in US ',
       ' Citizen Less than High School  Education ',
       ' Citizen High School  Graduate ',
       ' Citizen Some College  Education ', ' Citizen College Degree  ',
       ' Citizen Graduate or Professional Degree ',
       ' Total Citizen Income ', ' Citizen No Income ',
       'Citizen Income $1-$9,999', 'Citizen Income $10,000-$14,999',
       'Citizen Income $15,000-$24,999', 'Citizen Income $25,000-$34,999',
       'Citizen Income $35,000-$49,999', 'Citizen Income $50,000-$64,999',
       'Citizen Income $65,000-$74,999', 'Citizen Income $75,000 +',
       ' Total Population ', ' One Race Population ', ' White Race ',
       ' Black Race ', ' Native American Race ', ' Asian Race ',
       ' Pacific Islander Race ', ' Other Race Alone ',
     

__Take Away__

There are 37 features plus the 2 target features that will be tested while running different decision tree models: COVID Confirmed Cases and COVID Deaths. 

Testing features that have shown to impact COVID cases.
1. Income and 
2. Race (Specifically 'Black Race' and 'Hispantic or Latino')

In [ ]:
# WORK ON THIS SECTION
confirmed_case = 'confirmed'
death = 'not survived'
fig, axes = plt.subplots(nrows=1, ncols=2,figsize=(10, 4))

low_income = df_tristate_cases[df_tristate_cases['Citizen Income $10,000-$14,999']=='female']

men = train_df[train_df['Sex']=='male']
ax = sns.distplot(women[women['Survived']==1].Age.dropna(), bins=18, label = survived, ax = axes[0], kde =False)
ax = sns.distplot(women[women['Survived']==0].Age.dropna(), bins=40, label = not_survived, ax = axes[0], kde =False)
ax.legend()
ax.set_title('Female')
ax = sns.distplot(men[men['Survived']==1].Age.dropna(), bins=18, label = survived, ax = axes[1], kde = False)
ax = sns.distplot(men[men['Survived']==0].Age.dropna(), bins=40, label = not_survived, ax = axes[1], kde = False)
ax.legend()
_ = ax.set_title('Male')

<a id = "30"> <h2> Decision Tree Model: Target Variable - COVID Confirmed Cases </h2> </a>
___

In [42]:
# ---------------------------------------------------------------------------------------------------
# Extract needed features as a list of columns 
# excluding target variable 'COVID Confirmed Cases' 
# ---------------------------------------------------------------------------------------------------
## create a list of all the columns
list_all_columns = df_tristate_cases.columns.tolist()

## remove features in list, which are not needed for testing for feature selection, namely:
list_remove_features = ['NAME','Households SNAP', 'Total Families','Covid Confirmed Cases', 'Covid Deaths'] 

# Create sets of a,b
setA = set(list_all_columns)
setB = set(list_remove_features)

# Get new set with elements that are only in a but not in b
setlist_X_columns = setA.difference(list_remove_features)

# convert set object to a list
list_X_columns = list(setlist_X_columns)

# Define dependent variables
X = df_tristate_cases[list_X_columns].to_numpy()

#show the columns that need to be included as features
## sort alphabetically
list_X_columns.sort()
## show list 
list_X_columns

[' Asian Race ',
 ' Average Household Size ',
 ' Black Race ',
 ' Citizen College Degree  ',
 ' Citizen Graduate or Professional Degree ',
 ' Citizen High School  Graduate ',
 ' Citizen Less than High School  Education ',
 ' Citizen No Income ',
 ' Citizen Some College  Education ',
 ' Estimated Individuals SNAP ',
 ' Hispanic or Latino ',
 ' Households SNAP ',
 ' Native American Race ',
 ' One Race Population ',
 ' Other Race Alone ',
 ' Pacific Islander Race ',
 ' Total Citizen Educated in US ',
 ' Total Citizen Income ',
 ' Total Families ',
 ' Total Households ',
 ' Total Population ',
 ' White Race ',
 'Citizen Income $1-$9,999',
 'Citizen Income $10,000-$14,999',
 'Citizen Income $15,000-$24,999',
 'Citizen Income $25,000-$34,999',
 'Citizen Income $35,000-$49,999',
 'Citizen Income $50,000-$64,999',
 'Citizen Income $65,000-$74,999',
 'Citizen Income $75,000 +',
 'Covid Case Rate (per 1000)',
 'Covid Death Rate (per 1000)',
 'Covid Deaths ',
 'Female Median Age',
 'Male Median A

In [43]:
# Define Features and Target variables
X = df_tristate_cases[list_X_columns]
Y = df_tristate_cases['Covid Confirmed Cases']

In [44]:
# Split dataset into training set and test set 
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=2019) 

In [45]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [46]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.0


In [47]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         304       0.00      0.00      0.00       1.0
         577       0.00      0.00      0.00       0.0
        2601       0.00      0.00      0.00       1.0
        3875       0.00      0.00      0.00       1.0
        4362       0.00      0.00      0.00       0.0
        4423       0.00      0.00      0.00       1.0
        5039       0.00      0.00      0.00       1.0
        5173       0.00      0.00      0.00       0.0
        8545       0.00      0.00      0.00       0.0
        8556       0.00      0.00      0.00       1.0
       10751       0.00      0.00      0.00       1.0
       10814       0.00      0.00      0.00       1.0
       11095       0.00      0.00      0.00       0.0
       22753       0.00      0.00      0.00       1.0
       24218       0.00      0.00      0.00       0.0
       25761       0.00      0.00      0.00       1.0
       26807       0.00      0.00      0.00       1.0
       34226       0.00    

/opt/tljh/user/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/tljh/user/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [31]:
print(metrics.confusion_matrix(y_test, y_pred))

[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]]
