## Decision Tree

<b> Table of Contents: </b>
<b> Target Variable: Death Rate Categories </b>
<br> [1.0 Basic Model Decision Tree Classifier - Death Rate](#123)
        <br> [1.1 Oversampling (SMOTE)](#1234)
        <br> [1.2 Cross Validation (Oversampling) - BEST RESULT](#12345)
        <br> [1.3 Cross Validation (Undersampling)](#123456)
<br> [2.0 Basic Model Decision Tree Classifier - Case Rate](#1234567)
        <br> [2.1 Oversampling (SMOTE)](#12345678)
        <br> [2.2 Cross Validation (Oversampling)](#123456789)
        <br> [2.3 Cross Validation (Undersampling)](#1234567891)


In [1]:
# import modules
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
import os
import matplotlib.pyplot as plt
from sklearn import tree, metrics

import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler 
from sklearn.metrics import confusion_matrix, classification_report 
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import NearMiss 

# Cross Validation packages
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score


# for plotting
import matplotlib.pyplot as plt
from sklearn.svm import SVC

# import module for gridsearch (to find optimal hyper-parameters)
from sklearn.model_selection import GridSearchCV

# import module (to test execution time of a codeblock to run)
import time

import warnings

from sklearn.model_selection import StratifiedKFold
from sklearn.svm import SVC

/opt/tljh/user/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/opt/tljh/user/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.ensemble.bagging module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
  warnings.warn(message, FutureWarning)
/opt/tljh/user/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.ensemble.base module is  deprecated in version 0.22 and will be removed in

In [2]:
# packages for Receiver Operating Characteristic (ROC) with cross validation
# source: https://scikit-learn.org/0.18/auto_examples/model_selection/plot_roc_crossval.html
print(__doc__)

import numpy as np
from scipy import interp
import matplotlib.pyplot as plt
from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import plot_roc_curve

Automatically created module for IPython interactive environment


# Basic Model - Target Variable 'Case Rate Categories'

In [3]:
df = pd.read_csv("final_case_data.csv")
df.head()

Total Population  Total Citizen Income  Hispanic or Latino  \
0             54571                 44109               53261   
1            182265                166364              174273   
2             27457                 21627               26070   
3             22915                 18743               22509   
4             57322                 46501               52696   

   Total Citizen Educated in US  Total Households  White Race  Total Families  \
0                         36757             20221        9643           14613   
1                        143022             73180       17105           41898   
2                         18434              9820       12875            6015   
3                         15859              7953        5047            5201   
4                         39475             21578         761           14106   

   Citizen College Degree  Citizen Some College  Education  \
0                    5316                            10697   
1                   29237                            45286   
2                    1403                             4707   
3                    1289                             3971   
4                    3416                            13583   

   Citizen Income over 75000  Citizen High School  Graduate  \
0                       5298                          12363   
1                      17954                          39771   
2                       1019                           6549   
3                        953                           6958   
4                       2690                          12740   

   Citizen No Income  Pacific Islander Race  \
0               6377                    466   
1              20201                   3631   
2               3968                    894   
3               4170                    185   
4              10165                   2347   

   Citizen Graduate or Professional Degree  Citizen Income 1-9999  \
0                                     3860                   6955   
1                                    14731                  25080   
2                                      815                   5090   
3                                      808                   3268   
4                                     1756                   6561   

   Citizen Less than High School  Education  Citizen Income 15000-24999  \
0                                      4521                        6000   
1                                     13997                       26852   
2                                      4960                        3419   
3                                      2833                        2926   
4                                      7980                        6956   

   Citizen Income 15000-24999.1  Citizen Income 35000-49999  \
0                          6000                        5727   
1                         26852                       21502   
2                          3419                        1820   
3                          2926                        1860   
4                          6956                        5639   

   Case Rate Categories  
0                     2  
1                     2  
2                     3  
3                     2  
4                     2

In [4]:
df.dtypes

Total Population                            int64
Total Citizen Income                        int64
Hispanic or Latino                          int64
Total Citizen Educated in US                int64
Total Households                            int64
White Race                                  int64
Total Families                              int64
Citizen College Degree                      int64
Citizen Some College  Education             int64
Citizen Income over 75000                   int64
Citizen High School  Graduate               int64
Citizen No Income                           int64
Pacific Islander Race                       int64
Citizen Graduate or Professional Degree     int64
Citizen Income 1-9999                       int64
Citizen Less than High School  Education    int64
Citizen Income 15000-24999                  int64
Citizen Income 15000-24999.1                int64
Citizen Income 35000-49999                  int64
Case Rate Categories                        int64


In [5]:
# trim the spaces of the cells from the csv file
df.columns = df.columns.to_series().apply(lambda x: x.strip())

In [6]:
# need to change int64 to cat type for target vars
df['Case Rate Categories'] = df['Case Rate Categories'].astype('category')

In [7]:
#df.dtypes
#check to see if types changed to cat -- YES

<a id = "123"> <h2> 1.0 Basic Model Decision Tree Classifier </h2> </a>

__Build the Model__

# Target Variable is 'Case Rate Categories'

In [59]:
# define dependent and independent variables

feature_cols = ['Total Population','Total Citizen Income','Hispanic or Latino','Total Citizen Educated in US',
                                    'Total Households','White Race','Total Families','Citizen College Degree','Citizen Some College  Education',
                                    'Citizen Income over 75000','Citizen High School  Graduate',
                                    'Citizen No Income','Pacific Islander Race','Citizen Graduate or Professional Degree',
                                    'Citizen Income 1-9999','Citizen Less than High School  Education',
                                     'Citizen Income 15000-24999','Citizen Income 15000-24999','Citizen Income 35000-49999',
                                    'Case Rate Categories']

X = df.iloc[:, :-1] # Features is all columns in the dataframe except the last column
Y = df.iloc[:, -1] # Target is the last column in the dataframe: 'Case Rate Categories'

In [9]:
# Split dataset into training set and test set 
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=2019)

In [10]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [11]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.5021231422505308


In [12]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.34      0.35      0.35        40
           1       0.62      0.65      0.63       431
           2       0.49      0.45      0.47       352
           3       0.18      0.23      0.20        75
           4       0.11      0.09      0.10        23
           5       0.06      0.05      0.05        21

    accuracy                           0.50       942
   macro avg       0.30      0.30      0.30       942
weighted avg       0.50      0.50      0.50       942



In [13]:
print(metrics.confusion_matrix(y_test, y_pred))

[[ 14  23   3   0   0   0]
 [ 19 279 110  16   4   3]
 [  7 121 160  50   8   6]
 [  0  15  36  17   3   4]
 [  1   4   8   5   2   3]
 [  0   6   9   4   1   1]]


# Creating Graph of Decision Tree

In [65]:
# source: https://www.datacamp.com/community/tutorials/decision-tree-classification-python
from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
from sklearn.exceptions import NotFittedError
import pydotplus


dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True, feature_names = feature_cols,class_names=['0','1'])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png('covid_census.png')
Image(graph.create_png())

# sizing of the decision tree 
check_is_fitted(decision_tree, 'tree_')
best_clf = grid_search.best_estimator_


NotFittedError: This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [64]:
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO  
from IPython.display import Image  
import pydotplus

dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True,feature_names = feature_cols,class_names=['0','1'])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png('COVID_case.png')
Image(graph.create_png())

NotFittedError: This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [66]:
import sklearn.datasets as datasets
from sklearn.tree import DecisionTreeClassifier

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt


# check for the sklearn version, it has to be 0.21
import sklearn
print(sklearn.__version__)

0.22.1


In [69]:
clf = DecisionTreeClassifier(max_depth=3) #max_depth is maximum number of levels in the tree
clf.fit(df.data, df.target)

plt.figure(figsize=(25,10))
a = plot_tree(clf, 
              feature_names=df.feature_names, 
              class_names=df.target_names, 
              filled=True, 
              rounded=True, 
              fontsize=14)

AttributeError: 'DataFrame' object has no attribute 'data'

<a id = "1234"> <h2> 1.1 Oversampling (SMOTE) </h2> </a>
We oversample the <b> training </b> dataset, because the classes within our target variable 'Revenue' are imbalanced:
* class 0: 84.53%
* class 1: 15.47%

Fore more information, click on detailed information from Prof. Jie Tao [link](https://github.com/DrJieTao/ba545-docs/blob/master/competition2/handling_imbalanced_data_part2.ipynb)

In [17]:
# Split dataset into training set and test set 
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=2019) 

sm = SMOTE(random_state = 2019) 
X_train_res, y_train_res = sm.fit_sample(X_train, y_train) 

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape)) 
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape)) 
  
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0)))

After OverSampling, the shape of train_X: (5958, 19)
After OverSampling, the shape of train_y: (5958,) 

After OverSampling, counts of label '1': 993
After OverSampling, counts of label '0': 993


/opt/tljh/user/lib/python3.6/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/opt/tljh/user/lib/python3.6/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/opt/tljh/user/lib/python3.6/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/opt/tljh/user/lib/python3.6/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, cate

The SMOTE Algorithm has oversampled the instances in the minority class and made it equal to majority class:
* Both classes (0 & 1) now have 7291 instances, the <b> training </b> dataset is balanced.
* Class 1 increased from 1340 instances to 7291 instances, an increase of 5951 instances of class 1.

In [18]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train_res, y_train_res)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# print classification report 
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.36      0.60      0.45        40
           1       0.64      0.56      0.60       431
           2       0.48      0.39      0.43       352
           3       0.18      0.28      0.22        75
           4       0.12      0.26      0.16        23
           5       0.12      0.29      0.16        21

    accuracy                           0.46       942
   macro avg       0.32      0.40      0.34       942
weighted avg       0.51      0.46      0.48       942



## Cross Validation Using KFold </b>
For more information on the topic, please click the following [link](https://stackabuse.com/cross-validation-and-grid-search-for-model-selection-in-python/).
<br> The details of the package are noted [here](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html).

<a id = "12345"> <h2> 1.2 Cross Validation (Oversampling)  </h2> </a>

In [19]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
#result = cross_val_score(gnb, X, Y, cv=kfold, scoring='accuracy')
result = cross_val_score(clf, X_train_res, y_train_res, cv=kfold, scoring='accuracy')

print('--------------------------------------------------------------------------')
print('All the accuracy results:')
print('--------------------------------------------------------------------------')
print(result, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the accuracy results:')
print('--------------------------------------------------------------------------')
print(round(result.mean(), 4), '\n')

print('--------------------------------------------------------------------------')
print('Conclusion: the average of the accuracy changed after applying Kfold:')
print('--------------------------------------------------------------------------')
print('from:')
print(round(metrics.accuracy_score(y_test, y_pred), 5))
print('to:')
print(round(result.mean(), 5))
print('This is because we only use: {0:0.2f}% of our dataset to train the model!'.format(((k_fold_split-1)/k_fold_split)*100))

--------------------------------------------------------------------------
All the accuracy results:
--------------------------------------------------------------------------
[0.75167785 0.74832215 0.72147651 0.76006711 0.7533557  0.74496644
 0.75       0.72986577 0.78319328 0.7512605 ] 

--------------------------------------------------------------------------
Average of all the accuracy results:
--------------------------------------------------------------------------
0.7494 

--------------------------------------------------------------------------
Conclusion: the average of the accuracy changed after applying Kfold:
--------------------------------------------------------------------------
from:
0.46178
to:
0.74942
This is because we only use: 90.00% of our dataset to train the model!


In [20]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
#result = cross_val_score(clf, X, Y, cv=kfold, scoring='accuracy')
# note: only a single metric is permitted for parameter 'scoring'
# for all parameters for scoring, see source:https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
result_f1_weighted = cross_val_score(clf, X_train_res, y_train_res, cv=kfold, scoring='f1_weighted')
print('--------------------------------------------------------------------------')
print('All the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(result_f1_weighted, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(round(result_f1_weighted.mean(), 4), '\n')

--------------------------------------------------------------------------
All the weighted f1 results:
--------------------------------------------------------------------------
[0.73990512 0.74035919 0.71233377 0.7609838  0.74278282 0.75002915
 0.74989434 0.72715726 0.76600333 0.74550212] 

--------------------------------------------------------------------------
Average of all the weighted f1 results:
--------------------------------------------------------------------------
0.7435 



<a id = "123456"> <h2> 1.3 Cross Validation (Undersampling)  </h2> </a>

In [21]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
result = cross_val_score(clf, X, Y, cv=kfold, scoring='accuracy')
#result = cross_val_score(clf, X_train_miss, y_train_miss, cv=kfold, scoring='accuracy')

print('--------------------------------------------------------------------------')
print('All the accuracy results:')
print('--------------------------------------------------------------------------')
print(result, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the accuracy results:')
print('--------------------------------------------------------------------------')
print(round(result.mean(), 4), '\n')

print('--------------------------------------------------------------------------')
print('Conclusion: the average of the accuracy changed after applying Kfold:')
print('--------------------------------------------------------------------------')
print('from:')
print(round(metrics.accuracy_score(y_test, y_pred), 5))
print('to:')
print(round(result.mean(), 5))
print('This is because we only use: {0:0.2f}% of our dataset to train the model!'.format(((k_fold_split-1)/k_fold_split)*100))

--------------------------------------------------------------------------
All the accuracy results:
--------------------------------------------------------------------------
[0.46178344 0.49044586 0.44585987 0.50955414 0.45859873 0.43630573
 0.44585987 0.49044586 0.43630573 0.46964856] 

--------------------------------------------------------------------------
Average of all the accuracy results:
--------------------------------------------------------------------------
0.4645 

--------------------------------------------------------------------------
Conclusion: the average of the accuracy changed after applying Kfold:
--------------------------------------------------------------------------
from:
0.46178
to:
0.46448
This is because we only use: 90.00% of our dataset to train the model!


In [22]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
result = cross_val_score(clf, X, Y, cv=kfold, scoring='accuracy')
# note: only a single metric is permitted for parameter 'scoring'
# for all parameters for scoring, see source:https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
#result_f1_weighted = cross_val_score(clf, X_train_miss, y_train_miss, cv=kfold, scoring='f1_weighted')
print('--------------------------------------------------------------------------')
print('All the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(result_f1_weighted, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(round(result_f1_weighted.mean(), 4), '\n')

--------------------------------------------------------------------------
All the weighted f1 results:
--------------------------------------------------------------------------
[0.73990512 0.74035919 0.71233377 0.7609838  0.74278282 0.75002915
 0.74989434 0.72715726 0.76600333 0.74550212] 

--------------------------------------------------------------------------
Average of all the weighted f1 results:
--------------------------------------------------------------------------
0.7435 



<a id = "800150"> <h2> 1.5 Model Tuning (Hyperparameters) </h2> </a>
___


<b> Define Grid

In [23]:
criterion= ['gini', 'entropy'] 
splitter= ['best', 'random'] 
max_depth= [3,5,10] 
param_grid = dict(criterion=criterion, splitter=splitter, max_depth=max_depth)

<b> Hyper-parameter tweaking on oversampled training set

In [24]:
# set the start time
start = time.time()

# define the model
clf = DecisionTreeClassifier()

# Create a grid search object
grid = GridSearchCV(estimator=clf, param_grid=param_grid, cv = 3, n_jobs=-1)

# Fit the grid search (Fitting your model to the training data)
grid_result = grid.fit(X_train_res, y_train_res)

# define each optimal parameter as a new variable
optimal_criterion = grid.best_estimator_.get_params()['criterion']
optimal_splitter = grid.best_estimator_.get_params()['splitter']
optimal_max_depth = grid.best_estimator_.get_params()['max_depth']

# Summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

# get the time it takes for the gridsearch to run
# source: https://blog.softhints.com/python-test-performance-and-measure-time-elapsed-in-seconds/
# set the end time
end = time.time()

# get the elapsed execution time
execution_time = end - start
print("--- Execution time: ---")
print ('--- %0.3fms. --- ' % ( execution_time*1000.))
print("--- %s seconds ---" % (execution_time))
print("--- %s minutes ---" % (execution_time/60))

Best: 0.668681 using {'criterion': 'gini', 'max_depth': 10, 'splitter': 'best'}
--- Execution time: ---
--- 3504.790ms. --- 
--- 3.5047903060913086 seconds ---
--- 0.05841317176818848 minutes ---


<b> Applying the optimal hyper-parameters on oversampled training set

In [25]:
# apply the optimal hyper-parameters to the Logistic Regression Model
clf3 = DecisionTreeClassifier(criterion=optimal_criterion, splitter=optimal_splitter, max_depth=optimal_max_depth)

# fit/train the model with oversampled training set
clf3.fit(X_train_res, y_train_res)

# predict the testing set
y_pred=clf3.predict(X_test)

# print out the classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.24      0.55      0.34        40
           1       0.64      0.54      0.59       431
           2       0.48      0.30      0.37       352
           3       0.17      0.33      0.23        75
           4       0.06      0.17      0.09        23
           5       0.10      0.29      0.15        21

    accuracy                           0.42       942
   macro avg       0.28      0.36      0.29       942
weighted avg       0.50      0.42      0.44       942



<a id = "1234567"> <h2> 2.0 Basic Model Decision Tree Classifier 'Death Rate'</h2> </a>

# Target Variable is 'Death Rate Categories'

In [40]:
df2 = pd.read_csv("final_death_data.csv")
#df.head()

In [41]:
#df.info()

In [42]:
X = df2.iloc[:, :-1] # Features is all columns in the dataframe except the last column
Y = df2.iloc[:, -1] # Target is the last column in the dataframe: 'Death Rate Categories'

In [43]:
# Split dataset into training set and test set 
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=2019)

In [44]:
# Create Decision Tree classifer object
clf2 = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf2 = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf2.predict(X_test)

In [45]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.4607218683651805


In [46]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.66      0.64      0.65       390
           1       0.37      0.39      0.38       203
           2       0.33      0.36      0.35       228
           3       0.23      0.18      0.20        89
           4       0.12      0.11      0.12        27
           5       0.25      0.40      0.31         5

    accuracy                           0.46       942
   macro avg       0.33      0.35      0.33       942
weighted avg       0.46      0.46      0.46       942



In [47]:
print(metrics.confusion_matrix(y_test, y_pred))

[[251  54  70  12   3   0]
 [ 44  79  59  15   5   1]
 [ 55  54  83  26   8   2]
 [ 22  21  23  16   6   1]
 [  6   4  11   1   3   2]
 [  0   0   3   0   0   2]]


<a id = "12345678"> <h2> 2.1 Oversampling (SMOTE) </h2> </a>
We oversample the <b> training </b> dataset, because the classes within our target variable 'Revenue' are imbalanced:
* class 0: 84.53%
* class 1: 15.47%

Fore more information, click on detailed information from Prof. Jie Tao [link](https://github.com/DrJieTao/ba545-docs/blob/master/competition2/handling_imbalanced_data_part2.ipynb)

In [48]:
# Split dataset into training set and test set 
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=2019) 

sm = SMOTE(random_state = 2019) 
X_train_res, y_train_res = sm.fit_sample(X_train, y_train) 

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape)) 
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape)) 
  
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0)))

After OverSampling, the shape of train_X: (5202, 20)
After OverSampling, the shape of train_y: (5202,) 

After OverSampling, counts of label '1': 867
After OverSampling, counts of label '0': 867


/opt/tljh/user/lib/python3.6/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/opt/tljh/user/lib/python3.6/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/opt/tljh/user/lib/python3.6/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/opt/tljh/user/lib/python3.6/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, cate

The SMOTE Algorithm has oversampled the instances in the minority class and made it equal to majority class:
* Both classes (0 & 1) now have 7291 instances, the <b> training </b> dataset is balanced.
* Class 1 increased from 1340 instances to 7291 instances, an increase of 5951 instances of class 1.

In [49]:
# Create Decision Tree classifer object
clf2 = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf2 = clf2.fit(X_train_res, y_train_res)

#Predict the response for test dataset
y_pred = clf2.predict(X_test)

# print classification report 
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      0.60      0.64       390
           1       0.37      0.39      0.38       203
           2       0.31      0.31      0.31       228
           3       0.17      0.16      0.16        89
           4       0.05      0.11      0.07        27
           5       0.00      0.00      0.00         5

    accuracy                           0.42       942
   macro avg       0.26      0.26      0.26       942
weighted avg       0.46      0.42      0.44       942



## Cross Validation Using KFold </b>
For more information on the topic, please click the following [link](https://stackabuse.com/cross-validation-and-grid-search-for-model-selection-in-python/).
<br> The details of the package are noted [here](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html).

<a id = "123456789"> <h2> 2.2 Cross Validation (Oversampling)  </h2> </a>

In [50]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
#result = cross_val_score(gnb, X, Y, cv=kfold, scoring='accuracy')
result = cross_val_score(clf, X_train_res, y_train_res, cv=kfold, scoring='accuracy')

print('--------------------------------------------------------------------------')
print('All the accuracy results:')
print('--------------------------------------------------------------------------')
print(result, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the accuracy results:')
print('--------------------------------------------------------------------------')
print(round(result.mean(), 4), '\n')

print('--------------------------------------------------------------------------')
print('Conclusion: the average of the accuracy changed after applying Kfold:')
print('--------------------------------------------------------------------------')
print('from:')
print(round(metrics.accuracy_score(y_test, y_pred), 5))
print('to:')
print(round(result.mean(), 5))
print('This is because we only use: {0:0.2f}% of our dataset to train the model!'.format(((k_fold_split-1)/k_fold_split)*100))

--------------------------------------------------------------------------
All the accuracy results:
--------------------------------------------------------------------------
[0.72168906 0.66602687 0.73076923 0.74038462 0.71923077 0.69038462
 0.69230769 0.70384615 0.71923077 0.71153846] 

--------------------------------------------------------------------------
Average of all the accuracy results:
--------------------------------------------------------------------------
0.7095 

--------------------------------------------------------------------------
Conclusion: the average of the accuracy changed after applying Kfold:
--------------------------------------------------------------------------
from:
0.42463
to:
0.70954
This is because we only use: 90.00% of our dataset to train the model!


In [51]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
#result = cross_val_score(clf, X, Y, cv=kfold, scoring='accuracy')
# note: only a single metric is permitted for parameter 'scoring'
# for all parameters for scoring, see source:https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
result_f1_weighted = cross_val_score(clf, X_train_res, y_train_res, cv=kfold, scoring='f1_weighted')
print('--------------------------------------------------------------------------')
print('All the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(result_f1_weighted, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(round(result_f1_weighted.mean(), 4), '\n')

--------------------------------------------------------------------------
All the weighted f1 results:
--------------------------------------------------------------------------
[0.74115748 0.68317042 0.72982914 0.73576053 0.71780768 0.72596926
 0.68062536 0.72788834 0.71029462 0.71679411] 

--------------------------------------------------------------------------
Average of all the weighted f1 results:
--------------------------------------------------------------------------
0.7169 



<a id = "1234567891"> <h2> 2.3 Cross Validation (Undersampling)  </h2> </a>

In [53]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
result = cross_val_score(clf2, X, Y, cv=kfold, scoring='accuracy')
#result = cross_val_score(clf2, X_train_miss, y_train_miss, cv=kfold, scoring='accuracy')

print('--------------------------------------------------------------------------')
print('All the accuracy results:')
print('--------------------------------------------------------------------------')
print(result, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the accuracy results:')
print('--------------------------------------------------------------------------')
print(round(result.mean(), 4), '\n')

print('--------------------------------------------------------------------------')
print('Conclusion: the average of the accuracy changed after applying Kfold:')
print('--------------------------------------------------------------------------')
print('from:')
print(round(metrics.accuracy_score(y_test, y_pred), 5))
print('to:')
print(round(result.mean(), 5))
print('This is because we only use: {0:0.2f}% of our dataset to train the model!'.format(((k_fold_split-1)/k_fold_split)*100))

--------------------------------------------------------------------------
All the accuracy results:
--------------------------------------------------------------------------
[0.48089172 0.45541401 0.44585987 0.45859873 0.41082803 0.44585987
 0.41719745 0.45859873 0.46178344 0.41533546] 

--------------------------------------------------------------------------
Average of all the accuracy results:
--------------------------------------------------------------------------
0.445 

--------------------------------------------------------------------------
Conclusion: the average of the accuracy changed after applying Kfold:
--------------------------------------------------------------------------
from:
0.42463
to:
0.44504
This is because we only use: 90.00% of our dataset to train the model!


In [55]:
# Build the k-fold cross-validator
k_fold_split = 10
kfold = KFold(n_splits=k_fold_split, random_state=2019, shuffle=True)
#esult = cross_val_score(clf, X, Y, cv=kfold, scoring='accuracy')
# note: only a single metric is permitted for parameter 'scoring'
# for all parameters for scoring, see source:https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
#result_f1_weighted = cross_val_score(clf2, X_train_miss, y_train_miss, cv=kfold, scoring='f1_weighted')
print('--------------------------------------------------------------------------')
print('All the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(result_f1_weighted, '\n')

print('--------------------------------------------------------------------------')
print('Average of all the weighted f1 results:')
print('--------------------------------------------------------------------------')
print(round(result_f1_weighted.mean(), 4), '\n')

--------------------------------------------------------------------------
All the weighted f1 results:
--------------------------------------------------------------------------
[0.74115748 0.68317042 0.72982914 0.73576053 0.71780768 0.72596926
 0.68062536 0.72788834 0.71029462 0.71679411] 

--------------------------------------------------------------------------
Average of all the weighted f1 results:
--------------------------------------------------------------------------
0.7169 



<a id = "12345678912"> <h2> 2.4 Model Tuning (Hyperparameters) </h2> </a>
___


<b> Define Grid

In [56]:
criterion= ['gini', 'entropy'] 
splitter= ['best', 'random'] 
max_depth= [3,5,10] 
param_grid = dict(criterion=criterion, splitter=splitter, max_depth=max_depth)

<b> Hyper-parameter tweaking on oversampled training set

In [57]:
# set the start time
start = time.time()

# define the model
clf = DecisionTreeClassifier()

# Create a grid search object
grid = GridSearchCV(estimator=clf, param_grid=param_grid, cv = 3, n_jobs=-1)

# Fit the grid search (Fitting your model to the training data)
grid_result = grid.fit(X_train_res, y_train_res)

# define each optimal parameter as a new variable
optimal_criterion = grid.best_estimator_.get_params()['criterion']
optimal_splitter = grid.best_estimator_.get_params()['splitter']
optimal_max_depth = grid.best_estimator_.get_params()['max_depth']

# Summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

# get the time it takes for the gridsearch to run
# source: https://blog.softhints.com/python-test-performance-and-measure-time-elapsed-in-seconds/
# set the end time
end = time.time()

# get the elapsed execution time
execution_time = end - start
print("--- Execution time: ---")
print ('--- %0.3fms. --- ' % ( execution_time*1000.))
print("--- %s seconds ---" % (execution_time))
print("--- %s minutes ---" % (execution_time/60))

Best: 0.645905 using {'criterion': 'entropy', 'max_depth': 10, 'splitter': 'best'}
--- Execution time: ---
--- 3470.572ms. --- 
--- 3.470571994781494 seconds ---
--- 0.05784286657969157 minutes ---


<b> Applying the optimal hyper-parameters on oversampled training set

In [58]:
# apply the optimal hyper-parameters to the Logistic Regression Model
clf3 = DecisionTreeClassifier(criterion=optimal_criterion, splitter=optimal_splitter, max_depth=optimal_max_depth)

# fit/train the model with oversampled training set
clf3.fit(X_train_res, y_train_res)

# predict the testing set
y_pred=clf3.predict(X_test)

# print out the classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.72      0.60      0.66       390
           1       0.37      0.43      0.40       203
           2       0.28      0.22      0.25       228
           3       0.15      0.20      0.17        89
           4       0.09      0.22      0.13        27
           5       0.10      0.20      0.13         5

    accuracy                           0.42       942
   macro avg       0.28      0.31      0.29       942
weighted avg       0.46      0.42      0.44       942

