# Decision Tree #

<b> Table of Contents: </b>
<br> [Import and Load the Dataset](#10)
<br> [Data Exploration and Analysis](#20)
<br> [Decision Tree Model: Target Variable - COVID Confirmed Cases](#30)
<br> [Decision Tree Model: Target Variable - COVID Deaths](#40)


<a id = "10"> <h2> Import and Load the Dataset </h2> </a>
___

_Import Modules_

In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.preprocessing import Normalizer

_Loading the Dataset_

In [2]:
# load the dataset
df_tristate_cases = pd.read_csv("tristate_data_cases.csv")

In [3]:
df_tristate_cases.head()

NAME  Population  Covid Case Rate (per 1000)  \
0       Albany County, New York      304204                  289.092188   
1     Allegany County, New York       48946                   53.140195   
2        Bronx County, New York     1385108                 1837.024983   
3       Broome County, New York      200600                  120.727817   
4  Cattaraugus County, New York       80317                   48.246324   

   Covid Death Rate (per 1000)   Households SNAP   \
0                    13.112911              15087   
1                     2.574266               2994   
2                   168.955056             184934   
3                     8.983051              13226   
4                     1.593685               5801   

    Estimated Individuals SNAP    Total Citizen Educated in US   \
0                         34247                          204833   
1                          7305                           30331   
2                        512267                          927374   
3                         30684                          129802   
4                         13980                           53201   

    Citizen Less than High School  Education   \
0                                       15255   
1                                        3219   
2                                      264309   
3                                       12429   
4                                        6188   

    Citizen High School  Graduate    Citizen Some College  Education   ...  \
0                            50589                              55932  ...   
1                            11464                               9645  ...   
2                           256066                             227450  ...   
3                            40700                              40265  ...   
4                            21015                              15930  ...   

    Pacific Islander Race    Other Race Alone    Hispanic or Latino   \
0                     4744                7647                289287   
1                      206                 557                 48276   
2                   351011               73243                643695   
3                     1912                5087                193822   
4                      305                1363                 78972   

   Median Age  Male Median Age  Female Median Age   Total Households   \
0        38.5             36.8               40.0              126251   
1        37.8             36.2               39.2               18208   
2        32.8             30.6               34.9              483449   
3        40.2             38.1               42.2               82167   
4        40.7             39.8               41.6               32263   

    Average Household Size    Total Families   Covid Confirmed Cases  
0                         2             60631                  87943  
1                         2             10576                   2601  
2                         3            368196                2544478  
3                         2             40559                  24218  
4                         2             18801                   3875  

[5 rows x 38 columns]

<a id = "20"> <h2> Data Exploration and Analysis </h2> </a>
___

In [4]:
df_tristate_cases.describe()

Population  Covid Case Rate (per 1000)  Covid Death Rate (per 1000)  \
count  9.100000e+01                   91.000000                    91.000000   
mean   3.488362e+05                  494.782434                    30.009640   
std    4.688670e+05                  569.681260                    36.520683   
min    4.836000e+03                   16.823179                     0.000000   
25%    6.495600e+04                   88.358613                     3.932980   
50%    1.492650e+05                  230.123991                    13.455905   
75%    4.678780e+05                  698.363567                    48.039981   
max    2.504700e+06                 2523.785079                   168.955056   

        Households SNAP    Estimated Individuals SNAP   \
count          91.000000                     91.000000   
mean        18293.857143                  47275.835165   
std         35039.232590                  93199.614618   
min           112.000000                    235.000000   
25%          3339.000000                   8134.500000   
50%          6896.000000                  17693.000000   
75%         16277.000000                  41301.500000   
max        231794.000000                 623526.000000   

        Total Citizen Educated in US   \
count                    9.100000e+01   
mean                     2.451077e+05   
std                      3.390094e+05   
min                      3.604000e+03   
25%                      4.454750e+04   
50%                      9.567900e+04   
75%                      3.225095e+05   
max                      1.789355e+06   

        Citizen Less than High School  Education   \
count                                   91.000000   
mean                                 30821.109890   
std                                  58806.714504   
min                                    441.000000   
25%                                   4884.500000   
50%                                   9121.000000   
75%                                  29749.500000   
max                                 345445.000000   

        Citizen High School  Graduate    Citizen Some College  Education   \
count                        91.000000                          91.000000   
mean                      65796.329670                       59239.230769   
std                       84838.264728                       73146.413099   
min                        1155.000000                        1286.000000   
25%                       15221.000000                       13450.500000   
50%                       31537.000000                       26080.000000   
75%                       85696.000000                       78371.000000   
max                      461228.000000                      376485.000000   

        Citizen College Degree    ...   Pacific Islander Race   \
count                  91.000000  ...                91.000000   
mean                51549.593407  ...             24173.087912   
std                 78263.212835  ...             57081.322656   
min                   313.000000  ...                 4.000000   
25%                  5913.000000  ...               526.000000   
50%                 18515.000000  ...              2211.000000   
75%                 64578.500000  ...             18173.000000   
max                397987.000000  ...            351011.000000   

        Other Race Alone    Hispanic or Latino   Median Age  Male Median Age  \
count           91.000000          9.100000e+01   91.000000        91.000000   
mean         10097.010989          2.889334e+05   40.156044        38.840659   
std          17237.898715          3.622369e+05    3.098071         3.229894   
min             53.000000          4.785000e+03   29.800000        28.500000   
25%           1006.500000          6.262450e+04   38.500000        37.000000   
50%           3036.000000          1.266640e+05   40.400000        39.200000   
75%          11900.000000          3.770460e+05   41.700000        4

In [5]:
df_tristate_cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 38 columns):
NAME                                          91 non-null object
Population                                    91 non-null int64
Covid Case Rate (per 1000)                    91 non-null float64
Covid Death Rate (per 1000)                   91 non-null float64
 Households SNAP                              91 non-null int64
 Estimated Individuals SNAP                   91 non-null int64
 Total Citizen Educated in US                 91 non-null int64
 Citizen Less than High School  Education     91 non-null int64
 Citizen High School  Graduate                91 non-null int64
 Citizen Some College  Education              91 non-null int64
 Citizen College Degree                       91 non-null int64
 Citizen Graduate or Professional Degree      91 non-null int64
 Total Citizen Income                         91 non-null int64
 Citizen No Income                            91 non-null in

In [6]:
df_tristate_cases.columns.values

array(['NAME', 'Population', 'Covid Case Rate (per 1000)',
       'Covid Death Rate (per 1000)', ' Households SNAP ',
       ' Estimated Individuals SNAP ', ' Total Citizen Educated in US ',
       ' Citizen Less than High School  Education ',
       ' Citizen High School  Graduate ',
       ' Citizen Some College  Education ', ' Citizen College Degree  ',
       ' Citizen Graduate or Professional Degree ',
       ' Total Citizen Income ', ' Citizen No Income ',
       'Citizen Income $1-$9,999', 'Citizen Income $10,000-$14,999',
       'Citizen Income $15,000-$24,999', 'Citizen Income $25,000-$34,999',
       'Citizen Income $35,000-$49,999', 'Citizen Income $50,000-$64,999',
       'Citizen Income $65,000-$74,999', 'Citizen Income $75,000 +',
       ' Total Population ', ' One Race Population ', ' White Race ',
       ' Black Race ', ' Native American Race ', ' Asian Race ',
       ' Pacific Islander Race ', ' Other Race Alone ',
       ' Hispanic or Latino ', 'Median Age', 'Male Med

__Take Away__

There are 37 features plus the 2 target features that will be tested while running different decision tree models: COVID Confirmed Cases and COVID Deaths. 

Testing features that have shown to impact COVID cases.
1. Income and 
2. Race (Specifically 'Black Race' and 'Hispantic or Latino')

In [ ]:
# WORK ON THIS SECTION
confirmed_case = 'confirmed'
death = 'not survived'
fig, axes = plt.subplots(nrows=1, ncols=2,figsize=(10, 4))

low_income = df_tristate_cases[df_tristate_cases['Citizen Income $10,000-$14,999']=='female']

men = train_df[train_df['Sex']=='male']
ax = sns.distplot(women[women['Survived']==1].Age.dropna(), bins=18, label = survived, ax = axes[0], kde =False)
ax = sns.distplot(women[women['Survived']==0].Age.dropna(), bins=40, label = not_survived, ax = axes[0], kde =False)
ax.legend()
ax.set_title('Female')
ax = sns.distplot(men[men['Survived']==1].Age.dropna(), bins=18, label = survived, ax = axes[1], kde = False)
ax = sns.distplot(men[men['Survived']==0].Age.dropna(), bins=40, label = not_survived, ax = axes[1], kde = False)
ax.legend()
_ = ax.set_title('Male')

<a id = "30"> <h2> Decision Tree Model: Target Variable - COVID Confirmed Cases </h2> </a>
___

In [7]:
# ---------------------------------------------------------------------------------------------------
# Extract needed features as a list of columns 
# excluding target variable 'COVID Confirmed Cases' 
# ---------------------------------------------------------------------------------------------------
## create a list of all the columns
list_all_columns = df_tristate_cases.columns.tolist()

## remove features in list, which are not needed for testing for feature selection, namely:
list_remove_features = ['NAME','Households SNAP', 'Total Families','Covid Case Rate (per 1000)','Covid Death Rate (per 1000)','Covid Confirmed Cases'] 

# Create sets of a,b
setA = set(list_all_columns)
setB = set(list_remove_features)

# Get new set with elements that are only in a but not in b
setlist_X_columns = setA.difference(list_remove_features)

# convert set object to a list
list_X_columns = list(setlist_X_columns)

# Define dependent variables
X = df_tristate_cases[list_X_columns].to_numpy()

#show the columns that need to be included as features
## sort alphabetically
list_X_columns.sort()
## show list 
list_X_columns

[' Asian Race ',
 ' Average Household Size ',
 ' Black Race ',
 ' Citizen College Degree  ',
 ' Citizen Graduate or Professional Degree ',
 ' Citizen High School  Graduate ',
 ' Citizen Less than High School  Education ',
 ' Citizen No Income ',
 ' Citizen Some College  Education ',
 ' Estimated Individuals SNAP ',
 ' Hispanic or Latino ',
 ' Households SNAP ',
 ' Native American Race ',
 ' One Race Population ',
 ' Other Race Alone ',
 ' Pacific Islander Race ',
 ' Total Citizen Educated in US ',
 ' Total Citizen Income ',
 ' Total Families ',
 ' Total Households ',
 ' Total Population ',
 ' White Race ',
 'Citizen Income $1-$9,999',
 'Citizen Income $10,000-$14,999',
 'Citizen Income $15,000-$24,999',
 'Citizen Income $25,000-$34,999',
 'Citizen Income $35,000-$49,999',
 'Citizen Income $50,000-$64,999',
 'Citizen Income $65,000-$74,999',
 'Citizen Income $75,000 +',
 'Female Median Age',
 'Male Median Age',
 'Median Age',
 'Population']

In [8]:
# Define Features and Target variables
X = df_tristate_cases[list_X_columns]
Y = df_tristate_cases['Covid Confirmed Cases']

In [9]:
# Split dataset into training set and test set 
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=2019) 

In [10]:
# method 1 for decision tree
decision_tree = DecisionTreeClassifier() 
decision_tree.fit(X_train, y_train)  
y_pred = decision_tree.predict(X_test)  
acc_decision_tree = round(decision_tree.score(X_train, y_train) * 100, 2)


In [ ]:
# method 2 for decision tree 
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [11]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.0


In [12]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         304       0.00      0.00      0.00       1.0
         577       0.00      0.00      0.00       0.0
        2601       0.00      0.00      0.00       1.0
        2603       0.00      0.00      0.00       0.0
        3302       0.00      0.00      0.00       0.0
        3875       0.00      0.00      0.00       1.0
        3917       0.00      0.00      0.00       0.0
        4362       0.00      0.00      0.00       0.0
        4423       0.00      0.00      0.00       1.0
        5039       0.00      0.00      0.00       1.0
        5173       0.00      0.00      0.00       0.0
        5584       0.00      0.00      0.00       0.0
        7702       0.00      0.00      0.00       0.0
        8545       0.00      0.00      0.00       0.0
        8556       0.00      0.00      0.00       1.0
       10751       0.00      0.00      0.00       1.0
       10814       0.00      0.00      0.00       1.0
       13840       0.00    

/opt/tljh/user/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/tljh/user/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [13]:
print(metrics.confusion_matrix(y_test, y_pred))

[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


<a id = "40"> <h2> Decision Tree Model: Target Variable - COVID Deaths </h2> </a>
___

_Loading the Dataset_

In [13]:
# load the dataset
df_tristate_deaths = pd.read_csv("tristate_data_deaths.csv")

In [14]:
df_tristate_deaths.head()

NAME  Population  Covid Case Rate (per 1000)  \
0       Albany County, New York      304204                  289.092188   
1     Allegany County, New York       48946                   53.140195   
2        Bronx County, New York     1385108                 1837.024983   
3       Broome County, New York      200600                  120.727817   
4  Cattaraugus County, New York       80317                   48.246324   

   Covid Death Rate (per 1000)   Households SNAP   \
0                    13.112911              15087   
1                     2.574266               2994   
2                   168.955056             184934   
3                     8.983051              13226   
4                     1.593685               5801   

    Estimated Individuals SNAP    Total Citizen Educated in US   \
0                         34247                          204833   
1                          7305                           30331   
2                        512267                          927374   
3                         30684                          129802   
4                         13980                           53201   

    Citizen Less than High School  Education   \
0                                       15255   
1                                        3219   
2                                      264309   
3                                       12429   
4                                        6188   

    Citizen High School  Graduate    Citizen Some College  Education   ...  \
0                            50589                              55932  ...   
1                            11464                               9645  ...   
2                           256066                             227450  ...   
3                            40700                              40265  ...   
4                            21015                              15930  ...   

    Pacific Islander Race    Other Race Alone    Hispanic or Latino   \
0                     4744                7647                289287   
1                      206                 557                 48276   
2                   351011               73243                643695   
3                     1912                5087                193822   
4                      305                1363                 78972   

   Median Age  Male Median Age  Female Median Age   Total Households   \
0        38.5             36.8               40.0              126251   
1        37.8             36.2               39.2               18208   
2        32.8             30.6               34.9              483449   
3        40.2             38.1               42.2               82167   
4        40.7             39.8               41.6               32263   

    Average Household Size    Total Families   Covid Deaths   
0                         2             60631           3989  
1                         2             10576            126  
2                         3            368196         234021  
3                         2             40559           1802  
4                         2             18801            128  

[5 rows x 38 columns]

In [15]:
df_tristate_deaths.describe()

Population  Covid Case Rate (per 1000)  Covid Death Rate (per 1000)  \
count  9.100000e+01                   91.000000                    91.000000   
mean   3.488362e+05                  494.782434                    30.009640   
std    4.688670e+05                  569.681260                    36.520683   
min    4.836000e+03                   16.823179                     0.000000   
25%    6.495600e+04                   88.358613                     3.932980   
50%    1.492650e+05                  230.123991                    13.455905   
75%    4.678780e+05                  698.363567                    48.039981   
max    2.504700e+06                 2523.785079                   168.955056   

        Households SNAP    Estimated Individuals SNAP   \
count          91.000000                     91.000000   
mean        18293.857143                  47275.835165   
std         35039.232590                  93199.614618   
min           112.000000                    235.000000   
25%          3339.000000                   8134.500000   
50%          6896.000000                  17693.000000   
75%         16277.000000                  41301.500000   
max        231794.000000                 623526.000000   

        Total Citizen Educated in US   \
count                    9.100000e+01   
mean                     2.451077e+05   
std                      3.390094e+05   
min                      3.604000e+03   
25%                      4.454750e+04   
50%                      9.567900e+04   
75%                      3.225095e+05   
max                      1.789355e+06   

        Citizen Less than High School  Education   \
count                                   91.000000   
mean                                 30821.109890   
std                                  58806.714504   
min                                    441.000000   
25%                                   4884.500000   
50%                                   9121.000000   
75%                                  29749.500000   
max                                 345445.000000   

        Citizen High School  Graduate    Citizen Some College  Education   \
count                        91.000000                          91.000000   
mean                      65796.329670                       59239.230769   
std                       84838.264728                       73146.413099   
min                        1155.000000                        1286.000000   
25%                       15221.000000                       13450.500000   
50%                       31537.000000                       26080.000000   
75%                       85696.000000                       78371.000000   
max                      461228.000000                      376485.000000   

        Citizen College Degree    ...   Pacific Islander Race   \
count                  91.000000  ...                91.000000   
mean                51549.593407  ...             24173.087912   
std                 78263.212835  ...             57081.322656   
min                   313.000000  ...                 4.000000   
25%                  5913.000000  ...               526.000000   
50%                 18515.000000  ...              2211.000000   
75%                 64578.500000  ...             18173.000000   
max                397987.000000  ...            351011.000000   

        Other Race Alone    Hispanic or Latino   Median Age  Male Median Age  \
count           91.000000          9.100000e+01   91.000000        91.000000   
mean         10097.010989          2.889334e+05   40.156044        38.840659   
std          17237.898715          3.622369e+05    3.098071         3.229894   
min             53.000000          4.785000e+03   29.800000        28.500000   
25%           1006.500000          6.262450e+04   38.500000        37.000000   
50%           3036.000000          1.266640e+05   40.400000        39.200000   
75%          11900.000000          3.770460e+05   41.700000        4

In [24]:
df_tristate_deaths.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 38 columns):
NAME                                          91 non-null object
Population                                    91 non-null int64
Covid Case Rate (per 1000)                    91 non-null float64
Covid Death Rate (per 1000)                   91 non-null float64
 Households SNAP                              91 non-null int64
 Estimated Individuals SNAP                   91 non-null int64
 Total Citizen Educated in US                 91 non-null int64
 Citizen Less than High School  Education     91 non-null int64
 Citizen High School  Graduate                91 non-null int64
 Citizen Some College  Education              91 non-null int64
 Citizen College Degree                       91 non-null int64
 Citizen Graduate or Professional Degree      91 non-null int64
 Total Citizen Income                         91 non-null int64
 Citizen No Income                            91 non-null in

In [25]:
# ---------------------------------------------------------------------------------------------------
# Extract needed features as a list of columns 
# excluding target variable 'COVID Deaths' 
# ---------------------------------------------------------------------------------------------------
## create a list of all the columns
list_all_columns = df_tristate_deaths.columns.tolist()

## remove features in list, which are not needed for testing for feature selection, namely:
list_remove_features = ['NAME','Households SNAP', 'Total Families', 'Covid Case Rate (per 1000)', 'Covid Death Rate (per 1000)', 'Covid Deaths'] 

# Create sets of a,b
setA = set(list_all_columns)
setB = set(list_remove_features)

# Get new set with elements that are only in a but not in b
setlist_X_columns = setA.difference(list_remove_features)

# convert set object to a list
list_X_columns = list(setlist_X_columns)

# Define dependent variables
X = df_tristate_deaths[list_X_columns].to_numpy()

#show the columns that need to be included as features
## sort alphabetically
list_X_columns.sort()
## show list 
list_X_columns

[' Asian Race ',
 ' Average Household Size ',
 ' Black Race ',
 ' Citizen College Degree  ',
 ' Citizen Graduate or Professional Degree ',
 ' Citizen High School  Graduate ',
 ' Citizen Less than High School  Education ',
 ' Citizen No Income ',
 ' Citizen Some College  Education ',
 ' Estimated Individuals SNAP ',
 ' Hispanic or Latino ',
 ' Households SNAP ',
 ' Native American Race ',
 ' One Race Population ',
 ' Other Race Alone ',
 ' Pacific Islander Race ',
 ' Total Citizen Educated in US ',
 ' Total Citizen Income ',
 ' Total Families ',
 ' Total Households ',
 ' Total Population ',
 ' White Race ',
 'Citizen Income $1-$9,999',
 'Citizen Income $10,000-$14,999',
 'Citizen Income $15,000-$24,999',
 'Citizen Income $25,000-$34,999',
 'Citizen Income $35,000-$49,999',
 'Citizen Income $50,000-$64,999',
 'Citizen Income $65,000-$74,999',
 'Citizen Income $75,000 +',
 'Covid Deaths ',
 'Female Median Age',
 'Male Median Age',
 'Median Age',
 'Population']

In [26]:
# Define Features and Target variables
X = df_tristate_deaths[list_X_columns]
Y = df_tristate_deaths['Covid Deaths']

KeyError: 'Covid Deaths'

In [22]:
# Define Features and Target variables
# does not work because I want to drop certain columns 'NAME' is an obj
#X = df_tristate_deaths.iloc[:, :-1] #features is all columns in the df except the last column
#Y = df_tristate_deaths.iloc[:, -1] # target is the last column of the df 'Covid Deaths'

In [23]:
# Split dataset into training set and test set 
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=2019) 

ValueError: Found input variables with inconsistent numbers of samples: [90, 91]

In [21]:
# dont run yet
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

ValueError: could not convert string to float: 'Schoharie County, New York'

In [ ]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

In [ ]:
print(metrics.classification_report(y_test, y_pred))

In [ ]:
print(metrics.confusion_matrix(y_test, y_pred))